version: '2'
services:

  nginx:
    build: nginx
    networks:
      - local
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
  app:
    build: .
    networks:
      - local
    ports:
    - "3081"
    depends_on:
    - mypostgres
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/mydb
    - VIRTUAL_HOST=localhost
    links:
    - mypostgres
  mypostgres:
    build: postgres 
    networks:
      - local
    volumes:
       - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb

volumes:
  postgres-data:


networks:
  local:
