version: '2'
services:
  app:
    build: .
    network_mode: bridge
    expose:
    - 3081
    ports:
    - "3081:3081"
    depends_on:
    - mypostgres
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/mydb
    links:
    - mypostgres
  mypostgres:
    image: postgres:latest
    network_mode: bridge
    volumes:
       - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb

volumes:
  postgres-data:
